name: Maven Deploy to GitHub Releases

on:
  workflow_call:
    secrets:
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      BOT_PAT: ${{ secrets.BOT_PAT }}
    inputs:
      branch:
        required: true
        type: string
      repo_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check repo_name
        run: |
          if [ -z "${{ inputs.repo_name }}" ]; then
            echo "Error: repo_name is required."
            exit 1
          fi

      - name: Ensure main branch
        run: |
          if [ "${{ inputs.branch }}" != "main" ]; then
            echo "Error: This workflow can only be triggered for the 'main' branch."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create Maven settings.xml
        env:
          GITHUB_USERNAME: ${{ secrets.BOT_USERNAME }}
          GITHUB_PAT: ${{ secrets.BOT_PAT }}
        run: |
          cat > ${{ github.workspace }}/settings.xml <<EOF_
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>${GITHUB_USERNAME}</username>
                <password>${GITHUB_PAT}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <snapshots>
                      <enabled>false</enabled>
                    </snapshots>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/evildevsmk/${{ inputs.repo_name }}</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
          </settings>
          EOF_

      - name: Deploy with Maven
        run: mvn deploy -s ${{ github.workspace }}/settings.xml -f pom.xml -Pgithub
